import 'package:recetas_app/src/models/recipes_model.dart';

final List<Recipe> recipes = [
  Recipe(
    id: 1,
    name: 'Tacos al Pastor',
    category: 'almuerzo',
    time: '45 min',
    servings: 4,
    difficulty: 'Media',
    image: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?w=800',
    ingredients: [
      '500g de carne de cerdo',
      '2 piñas',
      '3 chiles guajillo',
      'Cebolla',
      'Cilantro',
      'Tortillas',
      'Limones',
    ],
    steps: [
      'Marinar la carne con chiles y especias por 2 horas',
      'Asar la carne en trompo o sartén',
      'Caramelizar la piña',
      'Cortar la carne en trozos pequeños',
      'Servir en tortillas con piña, cebolla y cilantro',
    ],
    rating: 4.8,
    calories: 420,
    trending: true,
  ),
  Recipe(
    id: 2,
    name: 'Ceviche Peruano',
    category: 'almuerzo',
    time: '30 min',
    servings: 4,
    difficulty: 'Fácil',
    image: 'https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=800',
    ingredients: [
      '500g pescado fresco',
      '10 limones',
      'Cebolla morada',
      'Ají limo',
      'Cilantro',
      'Camote',
      'Choclo',
      'Sal y pimienta',
    ],
    steps: [
      'Cortar el pescado en cubos',
      'Exprimir los limones',
      'Picar cebolla en juliana',
      'Mezclar pescado con limón, sal y ají',
      'Dejar reposar 5 minutos',
      'Servir con camote y choclo',
    ],
    rating: 4.9,
    calories: 280,
    featured: true,
  ),
  Recipe(
    id: 3,
    name: 'Pancakes Esponjosos',
    category: 'desayuno',
    time: '20 min',
    servings: 2,
    difficulty: 'Fácil',
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=800',
    ingredients: [
      '2 tazas de harina',
      '2 huevos',
      '1.5 tazas de leche',
      '2 cdas de azúcar',
      '1 cda de polvo de hornear',
      'Mantequilla',
      'Miel o jarabe',
    ],
    steps: [
      'Mezclar ingredientes secos',
      'Batir huevos con leche',
      'Combinar ambas mezclas',
      'Calentar sartén con mantequilla',
      'Verter mezcla y cocinar 2 min por lado',
      'Servir con miel',
    ],
    rating: 4.7,
    calories: 350,
  ),
  Recipe(
    id: 4,
    name: 'Lasagna Bolognesa',
    category: 'cena',
    time: '90 min',
    servings: 6,
    difficulty: 'Media',
    image: 'https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800',
    ingredients: [
      '500g carne molida',
      'Láminas de lasagna',
      '500ml salsa bechamel',
      '400g salsa de tomate',
      'Queso mozzarella',
      'Queso parmesano',
      'Cebolla y ajo',
      'Albahaca',
    ],
    steps: [
      'Preparar salsa boloñesa',
      'Cocinar láminas de pasta',
      'Preparar bechamel',
      'Armar capas: pasta, boloñesa, bechamel',
      'Cubrir con queso',
      'Hornear 40 min a 180°C',
    ],
    rating: 4.9,
    calories: 520,
    featured: true,
  ),
  Recipe(
    id: 5,
    name: 'Brownies de Chocolate',
    category: 'postre',
    time: '40 min',
    servings: 8,
    difficulty: 'Fácil',
    image: 'https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=800',
    ingredients: [
      '200g chocolate negro',
      '150g mantequilla',
      '3 huevos',
      '200g azúcar',
      '100g harina',
      '50g cacao en polvo',
      'Nueces (opcional)',
    ],
    steps: [
      'Derretir chocolate con mantequilla',
      'Batir huevos con azúcar',
      'Mezclar chocolate con huevos',
      'Incorporar harina y cacao',
      'Verter en molde engrasado',
      'Hornear 25 min a 180°C',
    ],
    rating: 4.8,
    calories: 380,
    trending: true,
  ),
];
